function Get-NISTCompliance {
    <#
    .SYNOPSIS
        Retrieves NIST 800-171 compliance data.

    .DESCRIPTION
        Reads the shared compliance data file generated by Invoke-ComplianceDataCollection.
        If the data file does not exist or -Refresh is specified, it triggers a new collection.

    .PARAMETER DataPath
        Path to the shared compliance data JSON file.
        Default: C:\ProgramData\osquery\nist_compliance_data.json

    .PARAMETER Refresh
        Force a new data collection cycle.

    .EXAMPLE
        Get-NISTCompliance
        Returns the current compliance status.

    .EXAMPLE
        Get-NISTCompliance -Refresh
        Collects fresh data and returns it.
    #>

    [CmdletBinding()]
    param(
        [string]$DataPath = "C:\ProgramData\osquery\nist_compliance_data.json",
        [switch]$Refresh
    )

    process {
        $scriptPath = Join-Path (Split-Path (Split-Path (Split-Path $PSScriptRoot -Parent) -Parent) -Parent) "scripts\Invoke-ComplianceDataCollection.ps1"

        if ($Refresh -or -not (Test-Path $DataPath)) {
            Write-Verbose "Collecting fresh compliance data..."
            
            if (-not (Test-Path $scriptPath)) {
                throw "Collection script not found at: $scriptPath"
            }

            # Run the collection script explicitly with PowerShell to avoid association issues
            # and keep window visible to debug hangs/prompts
            $params = @{ 
                FilePath = 'powershell.exe'
                ArgumentList = @("-ExecutionPolicy", "Bypass", "-File", $scriptPath)
                Wait = $true 
            }
            
            if ($DataPath -ne "C:\ProgramData\osquery\nist_compliance_data.json") {
                $params.ArgumentList += "-OutputPath `"$DataPath`""
            }
            
            Write-Verbose "Launching collection script: $scriptPath"
            Start-Process @params
            
            if (-not (Test-Path $DataPath)) {
                throw "Data collection failed to produce output at: $DataPath"
            }
        }

        Write-Verbose "Reading compliance data from: $DataPath"
        try {
            $data = Get-Content $DataPath -Raw | ConvertFrom-Json
            return $data
        }
        catch {
            Write-Error "Failed to read compliance data: $_"
        }
    }
}
